name = "pyunovel"
compatibility_date = "2024-02-08"

[[d1_databases]]
binding = "DB"
database_name = "pyunovel-db"
database_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
migrations_dir = "drizzle"

# R2 Bucket Local Setup
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "pyunovel-covers"
